/* ===== Gmail金融メール自動取込：既存OAuth設定・トークンキーを継承 ===== */
let gmailAccessToken=sessionStorage.getItem(GMAIL_TOKEN_KEY)||'',gmailTokenExpiresAt=Number(sessionStorage.getItem(GMAIL_TOKEN_EXP_KEY)||0),gmailSyncing=false,gmailLastAutoAttempt=0;

function gmailTokenValid(){return !!gmailAccessToken&&Date.now()<gmailTokenExpiresAt-60000}function gmailConnected(){return gmailTokenValid()}function gmailStatusLabel(){if(gmailConnected())return data.gmailSettings.emailAddress?`${data.gmailSettings.emailAddress} 接続中`:'Gmail 接続中';return data.gmailSettings.clientId?'未接続':'初期設定が必要'}
function formatSyncTime(v){if(!v)return'未同期';try{return new Date(v).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}catch(e){return'未同期'}}
function normalizeMerchantKey(v){return String(v||'').toLowerCase().replace(/[\s　・･ー\-_/\\()（）\[\]【】]/g,'').trim()}
const MERCHANT_CATEGORY_RULES=[
 ['交通費',['tap to pay','taptopay','jr西日本','jr東日本','jr東海','jr北海道','jr九州','jr四国','jr west','jr east','jr central','西日本旅客鉄道','東日本旅客鉄道','東海旅客鉄道','京都市交通局','京都市営地下鉄','京都市バス','kyoto city bus','kyoto subway','icoca','smart icoca','suica','モバイルsuica','pasmo','pitapa','交通系ic','スマートex','smart ex','ex予約','阪急電鉄','hankyu','京阪電気鉄道','keihan','近畿日本鉄道','kintetsu','近鉄','阪神電車','hanshin','南海電鉄','nankai','osaka metro','大阪メトロ','大阪市高速電気軌道','神戸市交通局','神戸市営地下鉄','神姫バス','京都バス','タクシー','taxi','uber taxi','go taxi','didi','高速バス','夜行バス']],
 ['食費',['セブンイレブン','7-eleven','7eleven','ファミリーマート','familymart','ローソン','lawson','ミニストップ','デイリーヤマザキ','マクドナルド','mcdonald','スターバックス','starbucks','ドトール','tully','タリーズ','すき家','松屋','吉野家','モスバーガー','ケンタッキー','kfc','サイゼリヤ','ガスト','ココス','スシロー','くら寿司','餃子の王将','丸亀製麺','なか卯','ミスタードーナツ','uber eats','出前館']],
 ['衣服費',['ジーユー','gu ','uniqlo','ユニクロ','しまむら','zara','h&m']],
 ['日用品',['無印良品','muji','ダイソー','daiso','seria','セリア','キャンドゥ','コーナン','ニトリ','ドンキホーテ','ドン・キホーテ','スギ薬局','マツモトキヨシ','ウエルシア','ココカラファイン','サンドラッグ','ドラッグ']],
 ['サブスク',['netflix','spotify','youtube premium','amazon prime','disney+','disney plus','icloud','adobe creative cloud']],
 ['娯楽費',['tohoシネマ','イオンシネマ','ラウンドワン','round1','カラオケ','ジャンカラ','快活club','ユナイテッドシネマ']],
 ['教育費',['大学','学校','紀伊國屋書店','丸善','ジュンク堂','教科書']],
 ['光熱費',['家賃','賃料','関西電力','大阪ガス','水道料金','電気料金','ガス料金','京都市上下水道']]
];
function categoryForMerchant(merchant,context=''){const key=normalizeMerchantKey(merchant),ctx=normalizeMerchantKey(context);if(!key&&!ctx)return null;const learned=Object.entries(data.merchantRules||{}).sort((a,b)=>b[0].length-a[0].length).find(([k])=>{const nk=normalizeMerchantKey(k);return nk&&(key===nk||(nk.length>=4&&key.includes(nk)))});if(learned&&data.categories.some(c=>c.name===learned[1]))return learned[1];if(key&&/amazon|アマゾン|apple|アップル|google|グーグル/.test(key))return null;for(const [cat,keys] of MERCHANT_CATEGORY_RULES)if((key&&keys.some(k=>key.includes(normalizeMerchantKey(k))))||(ctx&&keys.filter(k=>normalizeMerchantKey(k).length>=5).some(k=>ctx.includes(normalizeMerchantKey(k)))))return cat;return null}
async function onlineCategorizeMerchant(merchant){const q=String(merchant||'').trim();if(!q||q.length<2)return null;try{const u=new URL('https://ja.wikipedia.org/w/api.php');u.searchParams.set('action','query');u.searchParams.set('list','search');u.searchParams.set('srsearch',q);u.searchParams.set('format','json');u.searchParams.set('origin','*');u.searchParams.set('srlimit','3');const r=await fetch(u);if(!r.ok)return null;const j=await r.json(),txt=(j.query?.search||[]).map(x=>`${x.title} ${String(x.snippet||'').replace(/<[^>]+>/g,' ')}`).join(' ').toLowerCase();const rules=[['交通費',/鉄道|交通|バス|駅|航空|タクシー/],['食費',/飲食|レストラン|食品|コンビニ|カフェ|ファーストフード|スーパー/],['衣服費',/衣料|アパレル|ファッション|服飾/],['日用品',/雑貨|ドラッグストア|ホームセンター|家具|生活用品/],['娯楽費',/映画|娯楽|カラオケ|ゲーム|レジャー/],['教育費',/大学|学校|書店|教育/],['光熱費',/電力|ガス|水道|エネルギー/]];return rules.find(([,re])=>re.test(txt))?.[0]||null}catch(e){return null}}
function decodeBase64UrlUnicode(v){if(!v)return'';try{const b64=v.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(v.length/4)*4,'='),bin=atob(b64),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder('utf-8').decode(bytes)}catch(e){return''}}
function stripHtml(v){if(!v)return'';try{return new DOMParser().parseFromString(v,'text/html').body?.textContent||''}catch(e){return String(v).replace(/<[^>]+>/g,' ')}}
function gmailMessageText(payload){const plain=[],html=[];function walk(p){if(!p)return;const mime=String(p.mimeType||'').toLowerCase(),txt=decodeBase64UrlUnicode(p.body?.data||'');if(txt){if(mime.includes('text/plain'))plain.push(txt);else if(mime.includes('text/html'))html.push(stripHtml(txt))}(p.parts||[]).forEach(walk)}walk(payload);return (plain.length?plain:html).join('\n').replace(/\r/g,'\n').replace(/\n{3,}/g,'\n\n')}
function gmailHeaders(payload){const o={};for(const h of payload?.headers||[])o[String(h.name||'').toLowerCase()]=h.value||'';return o}
function detectMailSource(from,subject,body){const t=`${from}\n${subject}\n${body}`.toLowerCase();if(/paypay.*カード|paypay card/.test(t))return'PayPayカード';if(/三井住友カード|vpass|smbc card/.test(t))return'三井住友カード';if(/paypay銀行|paypay bank/.test(t))return'PayPay銀行';if(/sbi新生|sbishinsei|新生銀行/.test(t))return'SBI新生銀行';if(/ゆうちょ|japan post bank/.test(t))return'ゆうちょ銀行';if(/三井住友銀行|smbc\.co\.jp/.test(t))return'三井住友銀行';if(/楽天カード/.test(t))return'楽天カード';if(/jcb/.test(t))return'JCB';const m=String(from||'').match(/^\s*"?([^"<]+?)"?\s*</);return (m?.[1]||String(from||'Gmail')).trim().slice(0,40)}
function detectTransactionType(subject,body,source){const t=`${subject}\n${body}`.toLowerCase();if(/返金|取消|取り消し|キャンセル|refund/.test(t))return'refund';if(/請求額確定|ご請求額|請求金額のお知らせ|お支払い金額のお知らせ/.test(t)&&/カード|vpass|paypay/.test(t))return'card_statement';if(/デビット|debit/.test(t))return'debit_card';if(/cl利用|カード利用|カードご利用|ご利用のお知らせ|利用速報|利用通知|クレジット/.test(t))return'credit_card';if(/口座振替|口座引落|口座引き落とし|自動引落|引落し|引き落とし|引落/.test(t))return'bank_debit';if(/カード/.test(source)&&/利用|決済/.test(t))return'credit_card';return'unknown'}
function extractAmount(text){const t=String(text||'').replace(/[，]/g,',').replace(/[￥]/g,'¥'),pats=[/(?:ご利用金額|利用金額|ご利用額|決済金額|お支払い金額|引落金額|引き落とし金額|口座振替額|金額)\s*[：:]?\s*(?:¥\s*)?([0-9]{1,3}(?:,[0-9]{3})+|[0-9]{1,8})\s*円?/i,/(?:¥|JPY\s*)([0-9]{1,3}(?:,[0-9]{3})+|[0-9]{1,8})/i,/([0-9]{1,3}(?:,[0-9]{3})+)\s*円/i,/([0-9]{1,8})\s*円/i];for(const p of pats){const m=t.match(p);if(m){const n=Number(m[1].replace(/,/g,''));if(n>0&&n<100000000)return Math.round(n)}}return null}
function cleanMerchant(v){return String(v||'').replace(/[\t ]+/g,' ').replace(/[｜|].*$/,'').replace(/^(?:名称|店舗|加盟店)\s*[：:]?/,'').trim().slice(0,80)}
function extractMerchant(subject,body){const t=String(body||'').replace(/\r/g,''),pats=[/(?:ご利用先|利用先|ご利用店|利用店舗|加盟店名?|店舗名|ご利用内容|お取引内容|摘要|明細)\s*[：:]\s*([^\n]{2,100})/i,/(?:ご利用先|利用先|ご利用店|利用店舗|加盟店名?|店舗名|ご利用内容|お取引内容|摘要|明細)\s+([^\n]{2,100})/i];for(const p of pats){const m=t.match(p);if(m){const v=cleanMerchant(m[1]);if(v&&!/金額|日時|日付/.test(v))return v}}const sm=String(subject||'').match(/[「【\[]([^」】\]]{2,60})[」】\]]/);return sm?cleanMerchant(sm[1]):''}
function validYmd(y,m,d){y=Number(y);m=Number(m);d=Number(d);if(y<2000||y>2100||m<1||m>12||d<1||d>31)return null;const x=new Date(y,m-1,d);return x.getFullYear()===y&&x.getMonth()===m-1&&x.getDate()===d?`${y}-${pad(m)}-${pad(d)}`:null}
function referenceDateForMail(msg,headers={}){const hd=Date.parse(headers.date||'');if(Number.isFinite(hd))return new Date(hd);if(msg.internalDate&&Number.isFinite(Number(msg.internalDate)))return new Date(Number(msg.internalDate));return new Date()}
function inferYearForMonthDay(month,day,ref){const base=ref instanceof Date&&!Number.isNaN(ref.getTime())?ref:new Date();let best=null,diff=Infinity;for(const y of [base.getFullYear()-1,base.getFullYear(),base.getFullYear()+1]){const ds=validYmd(y,month,day);if(!ds)continue;const dd=Math.abs(parseYmd(ds)-base);if(dd<diff){best=ds;diff=dd}}return best}
function extractTransactionDate(subject,body,msg,headers={}){const text=`${subject||''}\n${body||''}`.replace(/\r/g,''),ref=referenceDateForMail(msg,headers),labels='(?:ご利用日時|利用日時|ご利用日|利用日|決済日時|決済日|取引日時|取引日|お取引日|購入日時|購入日)';let m=text.match(new RegExp(labels+'\\s*[：:]?\\s*(20\\d{2})[年\\/\\.\\-](\\d{1,2})[月\\/\\.\\-](\\d{1,2})(?:日)?','i'));if(m){const ds=validYmd(m[1],m[2],m[3]);if(ds)return ds}m=text.match(new RegExp(labels+'\\s*[：:]?\\s*(\\d{1,2})[月\\/\\.\\-](\\d{1,2})(?:日)?','i'));if(m){const ds=inferYearForMonthDay(m[1],m[2],ref);if(ds)return ds}m=text.match(/(20\d{2})[\/\.\-](\d{1,2})[\/\.\-](\d{1,2})[^\n]{0,28}(?:ご利用|利用|決済|取引)/i);if(m){const ds=validYmd(m[1],m[2],m[3]);if(ds)return ds}return ymd(ref)}
function matchFinancialEntity(source,type){const key=normalizeMerchantKey(source);if(type==='debit_card'){let d=data.debitCards.find(x=>{const n=normalizeMerchantKey(x.name);return n&&key&&(n.includes(key)||key.includes(n))});if(!d&&/三井住友|smbc|vpass|olive/i.test(String(source||'')))d=data.debitCards.find(x=>/olive/i.test(x.name))||data.debitCards.find(x=>/三井住友/i.test(bankById(x.bankId)?.name||''));return{method:'debit',id:d?.id||'',linkedBankId:d?.bankId||''}}if(type==='credit_card'){const c=data.cards.find(c=>[c.name,c.company].some(v=>{const n=normalizeMerchantKey(v);return n&&key&&(n.includes(key)||key.includes(n))}));return{method:'card',id:c?.id||''}}const b=data.banks.find(x=>{const n=normalizeMerchantKey(x.name);return n&&key&&(n.includes(key)||key.includes(n))});return{method:'bank',id:b?.id||'',linkedBankId:b?.id||''}}
async function parseFinancialMessage(msg){const h=gmailHeaders(msg.payload),subject=h.subject||'',from=h.from||'',body=gmailMessageText(msg.payload),sourceName=detectMailSource(from,subject,body),type0=detectTransactionType(subject,body,sourceName),amount=extractAmount(`${subject}
${body}`),combined=`${subject}
${body}`,financeWords=/利用|決済|デビット|クレジット|カード|口座振替|引落|引き落とし|支払い|返金|取消|請求|cl利用/i,ref=referenceDateForMail(msg,h),date=extractTransactionDate(subject,body,msg,h);if(sourceName==='三井住友カード'&&!(Number(amount)>0))return{id:uid('mail'),emailId:msg.id,threadId:msg.threadId||'',date,receivedAt:ref.toISOString(),from,subject,sourceName,type:type0,amount:0,merchant:'',category:'',categorySource:'',status:'ignored',direction:'expense',paymentMethod:'card',paymentId:'',excludedByUser:false,ignoredReason:'三井住友カード金額なし',createdAt:new Date().toISOString(),transactionId:'',bankApplied:false,bankReconciled:false,parserVersion:GMAIL_PARSER_VERSION};if(type0==='unknown'&&!financeWords.test(combined))return null;if(!amount&&type0==='unknown')return null;const merchant=extractMerchant(subject,body);let type=type0;if(type==='bank_debit'&&merchant&&/カード|vpass|paypayカード|visa.*カード/i.test(merchant))type='card_settlement';let category=categoryForMerchant(merchant,combined),categorySource=category?'rules':'';if(!category&&merchant){category=await onlineCategorizeMerchant(merchant);if(category)categorySource='online'}const entity=matchFinancialEntity(sourceName,type),selected=Array.isArray(data.gmailSettings.sourceIds)?data.gmailSettings.sourceIds:[],excluded=selected.length>0&&(!entity.id||!selected.includes(entity.id)),ignored=type==='card_statement'||type==='card_settlement'||excluded;return{id:uid('mail'),emailId:msg.id,threadId:msg.threadId||'',date,receivedAt:ref.toISOString(),from,subject,sourceName,type,amount:amount||0,merchant,category:category||'',categorySource,status:ignored?'ignored':(amount&&category&&merchant?'imported':'pending'),direction:type==='refund'?'refund':'expense',paymentMethod:entity.method,paymentId:entity.id,linkedBankId:entity.linkedBankId||'',excludedByUser:excluded,createdAt:new Date().toISOString(),transactionId:'',bankApplied:false,bankReconciled:false,parserVersion:GMAIL_PARSER_VERSION}}
function importMailToLedger(mi,{saveNow=true}={}){requireStateCommit('importMailToLedger');if(mi.status!=='imported'||!mi.amount||!mi.category)return null;const existing=data.transactions.find(x=>x.mailImportId===mi.id)||(mi.transactionId?data.transactions.find(x=>x.id===mi.transactionId):null);if(existing){mi.transactionId=existing.id;mi.linkedBankId=transactionBankId(existing);mi.bankApplied=!!existing.bankApplied;mi.bankReconciled=!!existing.bankReconciled;return existing}const args={date:mi.date,amount:mi.amount,category:mi.category,merchant:mi.merchant||mi.sourceName,paymentMethod:mi.paymentMethod,paymentId:mi.paymentId,linkedBankId:mi.linkedBankId||'',source:'gmail',mailImportId:mi.id,respectBalanceAsOf:true,eventAt:mi.receivedAt||`${mi.date}T12:00:00`,saveNow:false},tx=mi.direction==='refund'?recordRefund(args):recordExpense(args);mi.transactionId=tx?.id||'';mi.linkedBankId=transactionBankId(tx);mi.bankApplied=!!tx?.bankApplied;mi.bankReconciled=!!tx?.bankReconciled;if(saveNow)save();return tx}
function gmailRequestToken(forceConsent=false){return new Promise((resolve,reject)=>{const id=String(data.gmailSettings.clientId||'').trim();if(!id)return reject(new Error('Google OAuth クライアントIDを設定してください。'));if(!window.google?.accounts?.oauth2)return reject(new Error('Google認証ライブラリを読み込めませんでした。'));const tc=google.accounts.oauth2.initTokenClient({client_id:id,scope:GMAIL_SCOPE,callback:r=>{if(r?.error)return reject(new Error(r.error_description||r.error));gmailAccessToken=r.access_token||'';gmailTokenExpiresAt=Date.now()+(Number(r.expires_in)||3600)*1000;sessionStorage.setItem(GMAIL_TOKEN_KEY,gmailAccessToken);sessionStorage.setItem(GMAIL_TOKEN_EXP_KEY,String(gmailTokenExpiresAt));resolve(r)}});tc.requestAccessToken({prompt:forceConsent?'consent':''})})}
async function gmailFetch(url){const r=await fetch(url,{headers:{Authorization:`Bearer ${gmailAccessToken}`}});if(r.status===401){gmailAccessToken='';gmailTokenExpiresAt=0;sessionStorage.removeItem(GMAIL_TOKEN_KEY);sessionStorage.removeItem(GMAIL_TOKEN_EXP_KEY);throw new Error('Gmailの認証期限が切れました。再接続してください。')}if(!r.ok){let msg='';try{msg=(await r.json())?.error?.message||''}catch(e){}throw new Error(msg||`Gmail APIエラー (${r.status})`)}return r.json()}
async function refreshGmailProfile(){const p=await gmailFetch('https://gmail.googleapis.com/gmail/v1/users/me/profile');safeCommit(()=>{data.gmailSettings.emailAddress=p.emailAddress||''},{label:'gmail profile'})}
async function connectGmail(){try{await gmailRequestToken(true);await refreshGmailProfile();renderAll();await syncGmail()}catch(e){showAlert('Gmail接続に失敗しました',e.message)}}
function disconnectGmail(){const token=gmailAccessToken;try{safeCommit(()=>{data.gmailSettings.emailAddress=''},{label:'disconnect Gmail'})}catch(e){console.error('Gmail disconnect settings failed',e);return}gmailAccessToken='';gmailTokenExpiresAt=0;sessionStorage.removeItem(GMAIL_TOKEN_KEY);sessionStorage.removeItem(GMAIL_TOKEN_EXP_KEY);renderAll();try{if(token&&window.google?.accounts?.oauth2)google.accounts.oauth2.revoke(token,()=>{})}catch(e){console.error('Gmail token revocation failed',e)}}
function maybeAutoSyncGmail(force=false){if(!data.gmailSettings.autoSync||!gmailTokenValid()||gmailSyncing)return;const mins=Math.max(1,Number(data.gmailSettings.syncMinutes)||5),last=Date.parse(data.gmailSettings.lastSyncAt||0)||0;if(force||Date.now()-last>=mins*60000){if(Date.now()-gmailLastAutoAttempt<30000)return;gmailLastAutoAttempt=Date.now();syncGmail({silent:true})}}
function openGmailSettings(){
  let auto=!!data.gmailSettings.autoSync,selected=new Set(Array.isArray(data.gmailSettings.sourceIds)?data.gmailSettings.sourceIds:[]);
  const sources=[...data.banks.map(b=>({id:b.id,name:b.name,sub:'銀行口座',icon:'bank',color:'var(--blue)'})),...data.cards.map(c=>({id:c.id,name:c.name,sub:'クレジットカード',icon:'card',color:'var(--purple)'})),...data.debitCards.map(d=>({id:d.id,name:d.name,sub:`デビット・${bankById(d.bankId)?.name||'口座未設定'}`,icon:'wallet',color:'var(--teal)'}))];
  openSheet(`<div class="sheet-nav"><button type="button" class="nav-text" id="gsCancel">閉じる</button><div class="sheet-title">Gmail自動取得</div><button type="button" class="nav-text bold" id="gsSave">保存</button></div><div class="sheet-body"><div class="form-section"><div class="form-label">Google OAuth クライアントID</div><input class="field" id="gsClient" value="${esc(data.gmailSettings.clientId||'')}" placeholder="xxxxx.apps.googleusercontent.com"><div class="row-sub" style="margin-top:6px">既存のGoogle Cloud設定をそのまま使用できます。Client Secretは入力しません。</div></div><div class="form-section"><div class="form-label">自動反映する銀行・カード・デビット</div>${sources.length?`<div class="group">${sources.map(x=>`<button type="button" class="row press" data-gsource="${x.id}"><div class="settings-icon" style="background:${x.color}">${icon(x.icon)}</div><div class="row-main"><div class="row-title">${esc(x.name)}</div><div class="row-sub">${esc(x.sub)}</div></div><span class="source-check ${selected.has(x.id)?'on':''}">${selected.has(x.id)?icon('check'):''}</span></button>`).join('')}</div>`:'<div class="empty">銀行口座・カード・デビットを登録すると対象を選択できます。</div>'}<div class="row-sub">何も選択しない場合は、認識できるすべての金融メールを対象にします。</div></div><div class="form-section"><div class="form-label">Gmail検索条件</div><textarea class="field" id="gsQuery">${esc(data.gmailSettings.query||DEFAULT_DATA.gmailSettings.query)}</textarea></div><div class="form-section"><div class="form-label">起動中の自動同期間隔（分）</div><input class="field" id="gsMins" type="number" min="1" max="60" value="${Number(data.gmailSettings.syncMinutes)||5}"></div><div class="group"><div class="row"><div class="row-main"><div class="row-title">起動中に自動同期</div></div><button type="button" class="switch ${auto?'on':''}" id="gsAuto"></button></div></div><div class="card card-pad"><div class="row-title">接続状態</div><div class="hero-sub">${esc(gmailStatusLabel())}<br>最終同期 ${formatSyncTime(data.gmailSettings.lastSyncAt)}</div></div>${gmailConnected()?'<button type="button" class="primary" id="gsSync">今すぐ同期</button><button type="button" class="secondary" id="gsDisconnect" style="margin-top:10px">Gmail接続を解除</button>':'<button type="button" class="primary" id="gsConnect">Googleアカウントに接続</button>'}</div>`,'full',root=>{
    root.querySelector('#gsCancel').onclick=requestSheetClose;
    root.querySelector('#gsAuto').onclick=e=>{
      auto=!auto;
      e.currentTarget.classList.toggle('on',auto);
      markSheetDirty()
    };
    root.querySelectorAll('[data-gsource]').forEach(b=>b.onclick=()=>{
      const id=b.dataset.gsource;
      selected.has(id)?selected.delete(id):selected.add(id);
      markSheetDirty();
      const ck=b.querySelector('.source-check');
      ck.classList.toggle('on',selected.has(id));
      ck.innerHTML=selected.has(id)?icon('check'):''
    });
    const persist=()=>{
      const before=JSON.stringify((data.gmailSettings.sourceIds||[]).slice().sort());
      data.gmailSettings.clientId=root.querySelector('#gsClient').value.trim();
      data.gmailSettings.query=root.querySelector('#gsQuery').value.trim()||DEFAULT_DATA.gmailSettings.query;
      data.gmailSettings.syncMinutes=clamp(Number(root.querySelector('#gsMins').value)||5,1,60);
      data.gmailSettings.autoSync=auto;
      for(const id of selected)if(!bankById(id)&&!cardById(id)&&!debitById(id))throw new Error('Gmailの対象が存在しません');
      data.gmailSettings.sourceIds=[...selected];
      if(before!==JSON.stringify([...selected].sort()))data.mailImports.forEach(x=>{
        if(!mailEntityLocked(x))x.parserVersion=0
      });
      relinkMailEntities()
    };
    root.querySelector('#gsSave').onclick=()=>runSaveAction(root.querySelector('#gsSave'),persist,{label:'gmail settings',close:closeSheet});
    root.querySelector('#gsConnect')?.addEventListener('click',async()=>{
      if(await runSaveAction(root.querySelector('#gsConnect'),persist,{label:'gmail connect settings',close:closeSheet}))connectGmail()
    });
    root.querySelector('#gsSync')?.addEventListener('click',async()=>{
      if(await runSaveAction(root.querySelector('#gsSync'),persist,{label:'gmail sync settings',close:closeSheet}))syncGmail()
    });
    root.querySelector('#gsDisconnect')?.addEventListener('click',()=>{
      closeSheet();
      setTimeout(disconnectGmail,320)
    })
  })
}
function unknownMailListHtml(){const list=data.mailImports.filter(x=>x.status==='pending');return list.length?`<div class="group">${list.map(mi=>`<button type="button" class="row press" data-mi="${mi.id}" style="border-left:0;border-right:0;border-top:0"><div class="settings-icon" style="background:var(--orange)">${icon('help')}</div><div class="row-main"><div class="row-title">${esc(mi.merchant||mi.subject||mi.sourceName)}</div><div class="row-sub">${mi.date||'日付不明'}・${esc(mi.sourceName||'Gmail')}・${mi.amount?yen(mi.amount):'金額不明'}</div></div><span class="chev">›</span></button>`).join('')}</div>`:'<div class="empty">カテゴリー不明の取引はありません。</div>'}
function bindUnknownMailList(root){root.querySelectorAll('[data-mi]').forEach(b=>b.onclick=()=>openMailResolve(b.dataset.mi))}
function refreshUnknownMailView(){const top=pushStack[pushStack.length-1];if(!top||top.title!=='カテゴリー不明')return;const v=document.getElementById(top.id),body=v?.querySelector('.push-body');if(!body)return;body.innerHTML=unknownMailListHtml();bindUnknownMailList(body)}
function openUnknownMail(){return openMailOverview()}
let openMailResolve;
let openMailHistory;
function renderLock(){const l=document.getElementById('lockScreen');if(!data.security.enabled||!data.security.passcode){l.classList.remove('show');return}let entered='';l.classList.add('show');document.getElementById('lockDots').innerHTML=[0,1,2,3].map(()=>'<span class="lock-dot"></span>').join('');document.getElementById('lockPad').innerHTML=[1,2,3,4,5,6,7,8,9,'',0,'⌫'].map(k=>k===''?'<span></span>':`<button class="lock-key" data-lk="${k}">${k}</button>`).join('');const draw=()=>document.querySelectorAll('#lockDots .lock-dot').forEach((d,i)=>d.classList.toggle('on',i<entered.length));document.querySelectorAll('[data-lk]').forEach(b=>b.onclick=()=>{const k=b.dataset.lk;if(k==='⌫')entered=entered.slice(0,-1);else if(entered.length<4)entered+=k;draw();if(entered.length===4){if(entered===data.security.passcode){setTimeout(()=>l.classList.remove('show'),150)}else{entered='';draw();l.animate([{transform:'translateX(-8px)'},{transform:'translateX(8px)'},{transform:'translateX(0)'}],{duration:250})}}})}
let appHiddenAt=0;function handleVisibilityChange(){if(document.hidden){appHiddenAt=Date.now();return}if(data.security.enabled&&data.security.relock!=='never'&&appHiddenAt){const elapsed=Date.now()-appHiddenAt,delay=data.security.relock==='5m'?300000:data.security.relock==='1m'?60000:0;if(elapsed>=delay)renderLock()}if(document.visibilityState==='visible')maybeAutoSyncGmail(true)}document.addEventListener('visibilitychange',handleVisibilityChange)

/* === My Money 2.0 information architecture / Sidebar / Favorites / Tags === */
;